ALTER TABLE tasks DROP CONSTRAINT IF EXISTS fk_task_deal;
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS fk_task_lead;
ALTER TABLE events DROP CONSTRAINT IF EXISTS fk_event_deal;
ALTER TABLE events DROP CONSTRAINT IF EXISTS fk_event_lead;

ALTER TABLE tasks DROP COLUMN IF EXISTS deal_id;
ALTER TABLE tasks DROP COLUMN IF EXISTS lead_id;
ALTER TABLE events DROP COLUMN IF EXISTS deal_id;
ALTER TABLE events DROP COLUMN IF EXISTS lead_id;